#- name: initializing root password
#  shell: mysql --user=root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '{{ root_password }}'; FLUSH PRIVILEGES;"
#  tags: root_init
#  # when: rc == 0
#  ignore_errors: yes

- name: initiliazing root password
  community.mysql.mysql_user:
    name: root
    password: "{{ root_password }}"
    login_user: root
    login_password: ""
    login_unix_socket: /var/run/mysqld/mysqld.sock
  ignore_errors: yes

- name: remote access for root user
  community.mysql.mysql_user:
    name: "root"
    host: "%"
    password: "{{ root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_user: "root"
    login_password: "{{ root_password }}"
  tags: remote_root

- name: creating a normal user
  community.mysql.mysql_user:
    name: "dbuser"
    host: "%"
    password: "{{ user_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_user: "root"
    login_password: "{{ root_password }}"

- name: creating a database
  community.mysql.mysql_db:
    name: "mydb"
    state: present
    login_user: "root"
    login_password: "{{ root_password }}"
