command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

[iface]
label=
#instance=wlan0
#color=#00FF00
interval=10
separator=false

[bandwidth]
interval=5

[cpu_usage]
label=cpu
interval=10
min_width=CPU:100%
separator=true

[memory]
label=mem
interval=30
separator=true

[disk]
label=
interval=30
separator=true

[volume]
label=
instance=Master
interval=1
signal=10
command=/usr/share/i3blocks/volume 5 pulse
#install pavucontrol for controlling the volume
#install playerctl to control the volume from keybinds

[time]
command=date '+%d-%m-%Y %H:%M:%S'
interval=1

#[window title]
#command=xdotool getactivewindow getwindowname
#interval=1
#color=#A6D1FA
#min_width=1000
#align=center
